### ISSUE TITLE
Namespace Vte not available

### ISSUE THREAD

**Issue by labibrahman** [rbreaves/kinto#302]
**Describe the bug**
Upon installing kinto with setup.py, the GUI fails to appear.
When trying to run gui with suggested command kinto-gui.py, I get the following message:
`Traceback (most recent call last):
  File "/home/labib/.config/kinto/gui/kinto-gui.py", line 5, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available`

**Expected behavior**
After the install completed, the keyboard detection GUI would start on its own. If not then it would start after running the gui command. 
**Install Type:** Bare Metal - Macbook Air 2013
**Distro:** ElementaryOS 5.1.7 Hera
**DE:** Gnome
**Branch:** master
**Commit:** 1aa23c2

**Additional context**
This bug developed after kinto had already been installed successfully a day ago. I installed Kinto and was able to use it immediately. I later created a new user on my computer, and when attempting to install Kinto for that user encountered this error for the first time. After logging out of NewUser and returning to OriginalUser, I discovered that my Kinto install here had broken. I attempted to fix this by rebooting, uninstalling and then reinstalling Kinto, but none of these attempts were able to fix the problem

**Comment by rbreaves** [comment]
Hmmm I’ll do more testing under elementaryOS tomorrow. It probably just needs a vte-2.91 package installed.

Could be as simple as sudo apt install vte-2.91

**Comment by rbreaves** [comment]
Also Kinto isn’t really designed to work w/ more than 1 user. That will be coming in the next feature update however as I refuse to create a deb package or up it to a package manager repo until multiuser has been added.

**Comment by rbreaves** [comment]
Well.. I just tried reinstalling it with the latest master and did not run into such issues on that distro, and I want to restore back to an earlier base just to make no additional packages may have been installed but my VM became corrupted. I will revisit this a bit later as it is late, but I will try and address if I am able to replicate the problem.

In the meanwhile I encourage you to run this, as I know it's a package that could install and may help, even though this package was not installed on mine. I know other distros however do require it and I don't have an issue including it for elementaryOS as well - if needed, but it is a 130mb+ set of dependencies.. so I will only include it if I think it is really necessary. If there's a smaller package needed within that set then I will go with that.
```
sudo apt install vte-2.91
```

**Comment by labibrahman** [comment]
I tried installing vte-2.91 and running it again but it didn't work.
Assuming for now that my multi user attempt is what broke things. I nuked
my original install and started from scratch. Happy to report that it is
working perfectly once again. Thank you for looking into this so
thoroughly. This was my first time opening an issue against an open source
project and I'm really grateful for the help. Looking forward to seeing it
packaged up in a future version :)

**Comment by simakwm** [comment]
Just installed Hera on my macbook pro 2011 and some googling brought me here. Had the same issue without having multiple users; installing vte-2.91 solved it.
Thanks guys!

**Comment by edsonboldrini** [comment]
It worked

```sudo apt install vte-2.91```

**Comment by drod3763** [comment]
It happened to me on Arch Linux as well. I had to install the vte3 package to get it to work.

**Comment by sygibson** [comment]
I ran into this issue with OpenSUSE Tumbleweed linux desktop.  After install, received the following error:

```
shane@cosmic:~/bin$ ~/.config/kinto/gui/kinto-gui.py
Traceback (most recent call last):
  File "/home/shane/.config/kinto/gui/kinto-gui.py", line 7, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
```

I resolved the missing dependency issue with `sudo zypper install vte-devel`.

**Comment by zhuanhao-wu** [comment]
In the case where you tried installing all packages (in my case, it's `sudo apt install gir1.2-vte-2.91`) but still getting this error, you can try this:
Use dpkg to locate your vte typelib location, and add its including directory to an environment variable.

```
$ dpkg -L gir1.2-vte-2.91:amd64
...
/usr/lib/x86_64-linux-gnu/girepository-1.0/Vte-2.91.typelib
...
$ export GI_TYPELIB_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0
$~/.config/kinto/gui/kinto-gui.py
```
