### ISSUE TITLE
Could not run Kinto config etc.

### ISSUE THREAD

**Issue by nemonein** [rbreaves/kinto#317]
**Describe the bug**
Could not run Kinto config, Kinto service.. etc.

**Expected behavior**
?? A window open?

**Install Type:** Bare Metal
**Distro:** KDE Neon User edition latest version
**DE:** KDE
**Branch:** master
**Commit:** git rev-parse --short HEAD --> c71714e

Logs and status if relevant
```
# xkeysnail 
I think xkeysnail works good.

# xkb

systemctl --user status keyswap
Unit keyswap.service could not be found.

journalctl --user-unit=keyswap.service -b
-- Logs begin at Fri 2020-08-14 22:43:18 KST, end at Thu 2020-11-12 13:20:01 KST. --
-- No entries --
```

**Screenshots**

**Additional context**
When I click Kinto config on the tray icon, there's no response at all.

I run `~/.config/kinto/gui/kinto-gui.py` manually, then I click again.
Here are the message from the terminal.

```
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 623, in setConfig
    elif which(gedit) is not None:
NameError: name 'gedit' is not defined
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 635, in setService
    elif which(gedit) is not None:
NameError: name 'gedit' is not defined
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 694, in setSysKB
    Popen(['gnome-control-center','keyboard'])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: 'gnome-control-center'
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 700, in setRegion
    Popen(['gnome-control-center','region'])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: 'gnome-control-center'
```

*** 그런 파일이나 디렉터리가 없습니다 meaning 'There are no files or directories'

I'm on KDE, so gedit and gnome-control-center are not installed.

**Comment by rbreaves** [comment]
Try the latest, I have added 2 more default text editor options.

**Comment by rbreaves** [comment]
I'll need to look into what the equivalent is for the 'gnome-control-center' option for KDE. If you can provide that then I will add it later.

**Comment by rbreaves** [comment]
Actually re-reading those messages.. other Linux OS's set which as none when an app is not installed.. I am not sure why KDE is not behaving in the same manner.. I guess I will need to check for None or that type of error message that it is returning. I am calling it a night though. I will tackling this one again later.

**Comment by nemonein** [comment]
Thank you @rbreaves.
I tried with 4eea5c1, and nothing changed.

On 'Customize' menu, only 'Tweaks' works good(opens a window), and others does not respond.
Error messages are the same.
```
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 623, in setConfig
    elif which(gedit) is not None:
NameError: name 'gedit' is not defined
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 635, in setService
    elif which(gedit) is not None:
NameError: name 'gedit' is not defined
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 694, in setSysKB
    Popen(['gnome-control-center','keyboard'])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: 'gnome-control-center'
Traceback (most recent call last):
  File "/home/nemokden/.config/kinto/kintotray.py", line 700, in setRegion
    Popen(['gnome-control-center','region'])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 그런 파일이나 디렉터리가 없습니다: 'gnome-control-center'
```

**Comment by rbreaves** [comment]
Should be solved now. I tested it on my KDE Neon instance and it appeared to be fine.

**Comment by nemonein** [comment]
Yeah, it works now.
Thank you very much!

**Comment by rbreaves** [comment]
I would have liked opening straight to the system shortcuts panel but KDE splits it up weird, so I can't get you to a window with all options available and I wasn't prepared to add in 3 options for global, custom and whatever else shortcuts lol. I either dump you into system settings or a specific shortcut type - with no ability to go up a level to see the other shortcut types so I opted for system settings.
