### ISSUE TITLE
gnome-terminal shortcut remapping not working properly on wayland

### ISSUE THREAD

**Issue by prosac** [rbreaves/kinto#334]
**Firt things first**

Great tool! Thank you very much! No problems for me when running on X11, only on wayland. See below.

**Describe the bug**

Under Ubuntu 20.04 gnome wayland neither the original shortcuts for gnome-terminal work completely, nor the remapped ones. Under X11 it works great!

Example: Opening a new tab does not work via the remapped shortcut, but works using the original Ctrl-Shift-Tab, closing it via Ctrl-Shift-w does not work, though. So it seems to be kind of a mixed situation.

Other apps, like Firefox and Nautilus work fine.

**Expected behavior**

Super-t should open a new tab, Super-w should close it.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04
**DE:** Gnome __on wayland__
**Branch:** master
**Commit:** 5d37e72

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
● xkeysnail.service - xkeysnail
     Loaded: loaded (/lib/systemd/system/xkeysnail.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-11-26 17:39:49 CET; 15min ago
   Main PID: 69641 (sudo)
      Tasks: 2 (limit: 38206)
     Memory: 15.8M
     CGroup: /system.slice/xkeysnail.service
             ├─69641 /usr/bin/sudo /bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
             └─69642 /usr/bin/python3 /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py

Nov 26 17:39:49 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 17:39:49 nb-jvonbargen2 sudo[69641]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 17:39:49 nb-jvonbargen2 sudo[69641]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 17:39:49 nb-jvonbargen2 sudo[69643]: localuser:root being added to access control list



sudo journalctl --unit=xkeysnail.service -b
Nov 26 16:33:04 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 16:33:04 nb-jvonbargen2 sudo[56610]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 16:33:04 nb-jvonbargen2 sudo[56610]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 16:33:04 nb-jvonbargen2 sudo[56612]: localuser:root being added to access control list
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ██╗  ██╗██╗  ██╗███████╗██╗   ██╗
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ╚██╗██╔╝██║ ██╔╝██╔════╝╚██╗ ██╔╝
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:  ╚███╔╝ █████╔╝ █████╗   ╚████╔╝
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:  ██╔██╗ ██╔═██╗ ██╔══╝    ╚██╔╝
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ██╔╝ ██╗██║  ██╗███████╗   ██║
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   ███████╗███╗   ██╗ █████╗ ██╗██╗
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   ██╔════╝████╗  ██║██╔══██╗██║██║
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   ███████╗██╔██╗ ██║███████║██║██║
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   ╚════██║██║╚██╗██║██╔══██║██║██║
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   ███████║██║ ╚████║██║  ██║██║███████╗
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝╚══════╝
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:                              v0.3.0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: No keyboard devices specified via (--devices) option.
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: xkeysnail picks up keyboard-ish devices from the list below:
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: --------------------------------------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Device               Name                                Phys
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: --------------------------------------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event0    Lid Switch                          PNP0C0D/button/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event1    Power Button                        PNP0C0C/button/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event2    Sleep Button                        PNP0C0E/button/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event3    AT Translated Set 2 keyboard        isa0060/serio0/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event4    Video Bus                           LNXVIDEO/video/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event7    PS/2 Generic Mouse                  isa0060/serio1/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event8    SteelSeries  SteelSeries Arctis 7 Consumer Control usb-0000:00:14.0-1.6.1/input5
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event9    SteelSeries  SteelSeries Arctis 7   usb-0000:00:14.0-1.6.1/input5
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event14   G.SKILL Corporation G.SKILL RIPJAWS MX780 GAMING MOUSE usb-0000:00:14.0-1.6.4/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event15   G.SKILL Corporation G.SKILL RIPJAWS MX780 GAMING MOUSE Keyboard usb-0000:00:14.0-1.6.4/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event16   G.SKILL Corporation G.SKILL RIPJAWS MX780 GAMING MOUSE Consumer Control usb-0000:00:14.0-1.6.4/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event17   Intel HID events
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event18   Intel HID 5 button array
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event5    Integrated_Webcam_HD: Integrate     usb-0000:00:14.0-6/button
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event6    Dell WMI hotkeys
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event19   DELL08E1:00 06CB:CD97 Mouse         i2c-DELL08E1:00
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event20   DELL08E1:00 06CB:CD97 Touchpad      i2c-DELL08E1:00
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event21   HDA Intel PCH Headphone Mic         ALSA
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event22   HDA Intel PCH HDMI/DP,pcm=3         ALSA
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event23   HDA Intel PCH HDMI/DP,pcm=7         ALSA
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event24   HDA Intel PCH HDMI/DP,pcm=8         ALSA
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event25   HDA Intel PCH HDMI/DP,pcm=9         ALSA
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event26   HDA Intel PCH HDMI/DP,pcm=10        ALSA
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event10   ZSA Technology Labs Inc ErgoDox EZ Glow usb-0000:00:14.0-1.6.3/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event11   ZSA Technology Labs Inc ErgoDox EZ Glow System Control usb-0000:00:14.0-1.6.3/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event12   ZSA Technology Labs Inc ErgoDox EZ Glow Consumer Control usb-0000:00:14.0-1.6.3/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event13   ZSA Technology Labs Inc ErgoDox EZ Glow Keyboard usb-0000:00:14.0-1.6.3/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event27   py-evdev-uinput                     py-evdev-uinput
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Okay, now enable remapping on the following device(s):
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ------------------------------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Device               Name                                Phys
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ------------------------------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event3    AT Translated Set 2 keyboard        isa0060/serio0/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event15   G.SKILL Corporation G.SKILL RIPJAWS MX780 GAMING MOUSE Keyboard usb-0000:00:14.0-1.6.4/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event10   ZSA Technology Labs Inc ErgoDox EZ Glow usb-0000:00:14.0-1.6.3/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event13   ZSA Technology Labs Inc ErgoDox EZ Glow Keyboard usb-0000:00:14.0-1.6.3/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Watching keyboard devices plug in
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: No key event will be output since quiet option was specified.
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Device removed: ZSA Technology Labs Inc ErgoDox EZ Glow Keyboard
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Device removed: ZSA Technology Labs Inc ErgoDox EZ Glow Keyboard
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Okay, now enable remapping on the following new device(s):
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Device               Name                                Phys
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event10   ZSA Technology Labs Inc ErgoDox EZ Glow usb-0000:00:14.0-1.6.3/input0
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Okay, now enable remapping on the following new device(s):
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ---------------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Device               Name                                Phys
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: ---------------------------------------------------------------------------------------------------
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: /dev/input/event13   ZSA Technology Labs Inc ErgoDox EZ Glow Keyboard usb-0000:00:14.0-1.6.3/input1
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Traceback (most recent call last):
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 583, in send_and_recv
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     i = self.socket.send(self.data_send)
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: BrokenPipeError: [Errno 32] Broken pipe
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: During handling of the above exception, another exception occurred:
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Traceback (most recent call last):
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/bin/xkeysnail", line 6, in <module>
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     cli_main()
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/xkeysnail/__init__.py", line 65, in cli_main
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     loop(args.devices, args.watch, args.quiet)
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/xkeysnail/input.py", line 131, in loop
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     on_event(event, waitable.name, quiet)
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/xkeysnail/transform.py", line 388, in on_event
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     wm_class = get_active_window_wm_class()
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/xkeysnail/transform.py", line 19, in get_active_window_wm_class
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     current_window = display.get_input_focus().focus
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 607, in get_input_focus
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     return request.GetInputFocus(display = self.display)
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/rq.py", line 1369, in __init__
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     self.reply()
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/rq.py", line 1381, in reply
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     self._display.send_and_recv(request = self._serial)
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 586, in send_and_recv
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]:     raise self.socket_error
Nov 26 17:39:33 nb-jvonbargen2 sudo[56611]: Xlib.error.ConnectionClosedError: Display connection closed by server: [Errno 32] Broken pipe
Nov 26 17:39:34 nb-jvonbargen2 sudo[56610]: pam_unix(sudo:session): session closed for user root
Nov 26 17:39:34 nb-jvonbargen2 systemd[1]: xkeysnail.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 17:39:34 nb-jvonbargen2 systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Nov 26 17:39:37 nb-jvonbargen2 systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 1.
Nov 26 17:39:37 nb-jvonbargen2 systemd[1]: Stopped xkeysnail.
Nov 26 17:39:37 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 17:39:37 nb-jvonbargen2 sudo[69046]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 17:39:37 nb-jvonbargen2 sudo[69046]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 17:39:37 nb-jvonbargen2 sudo[69048]: /usr/bin/xhost:  unable to open display ":0"
Nov 26 17:39:37 nb-jvonbargen2 sudo[69046]: pam_unix(sudo:session): session closed for user root
Nov 26 17:39:37 nb-jvonbargen2 systemd[1]: xkeysnail.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 17:39:37 nb-jvonbargen2 systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Nov 26 17:39:40 nb-jvonbargen2 systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 2.
Nov 26 17:39:40 nb-jvonbargen2 systemd[1]: Stopped xkeysnail.
Nov 26 17:39:40 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 17:39:40 nb-jvonbargen2 sudo[69049]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 17:39:40 nb-jvonbargen2 sudo[69049]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 17:39:40 nb-jvonbargen2 sudo[69051]: /usr/bin/xhost:  unable to open display ":0"
Nov 26 17:39:40 nb-jvonbargen2 sudo[69049]: pam_unix(sudo:session): session closed for user root
Nov 26 17:39:40 nb-jvonbargen2 systemd[1]: xkeysnail.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 17:39:40 nb-jvonbargen2 systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Nov 26 17:39:43 nb-jvonbargen2 systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 3.
Nov 26 17:39:43 nb-jvonbargen2 systemd[1]: Stopped xkeysnail.
Nov 26 17:39:43 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 17:39:43 nb-jvonbargen2 sudo[69055]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 17:39:43 nb-jvonbargen2 sudo[69055]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 17:39:43 nb-jvonbargen2 sudo[69057]: /usr/bin/xhost:  unable to open display ":0"
Nov 26 17:39:43 nb-jvonbargen2 sudo[69055]: pam_unix(sudo:session): session closed for user root
Nov 26 17:39:43 nb-jvonbargen2 systemd[1]: xkeysnail.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 17:39:43 nb-jvonbargen2 systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Nov 26 17:39:46 nb-jvonbargen2 systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 4.
Nov 26 17:39:46 nb-jvonbargen2 systemd[1]: Stopped xkeysnail.
Nov 26 17:39:46 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 17:39:46 nb-jvonbargen2 sudo[69175]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 17:39:46 nb-jvonbargen2 sudo[69175]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 17:39:46 nb-jvonbargen2 sudo[69177]: /usr/bin/xhost:  unable to open display ":0"
Nov 26 17:39:46 nb-jvonbargen2 sudo[69175]: pam_unix(sudo:session): session closed for user root
Nov 26 17:39:46 nb-jvonbargen2 systemd[1]: xkeysnail.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 17:39:46 nb-jvonbargen2 systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Nov 26 17:39:49 nb-jvonbargen2 systemd[1]: Stopped xkeysnail.
Nov 26 17:39:49 nb-jvonbargen2 systemd[1]: Started xkeysnail.
Nov 26 17:39:49 nb-jvonbargen2 sudo[69641]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/johannes.vonbargen/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/johannes.vonbargen/.config/kinto/kinto.py
Nov 26 17:39:49 nb-jvonbargen2 sudo[69641]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 26 17:39:49 nb-jvonbargen2 sudo[69643]: localuser:root being added to access control list

# xkb
systemctl --user status keyswap
systemctl --user status keyswap
Unit keyswap.service could not be found.

journalctl --user-unit=keyswap.service -b
journalctl --user-unit=keyswap.service -b
Hint: You are currently not seeing messages from the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Tue 2020-11-17 16:16:36 CET, end at Thu 2020-11-26 17:59:32 CET. --
-- No entries --
```

**Additional context**
As seen in the logs i am using an external ErgoDox EZ Glow Keyboard

**Comment by rbreaves** [comment]
Dependent on this, you are welcomed to explore my Wayland branch of xkeysnail & reinstall xkeysnail from there..

https://github.com/mooz/xkeysnail/issues/108

Normally I’d close this ticket since it belongs further upstream but I’ll keep it. Maybe it’ll attract someone’s attention to help address the issue in a better way than I devised. I dislike it so much I didn’t completely implement it because I think it’s be a poor & unreliable experience unless it’s done better.

**Comment by prosac** [comment]
Thanks for the answer and thanks for your efforts! i will check out your xksnail branch and go back to X for work.

A little addition to my report: I was all based on a situation where I installed and originally started kinto while on X11 and then logged into a wayland session. I tested now to stop kinto under X11, log out and then log in using wayland to start kinto again (not re-installing, just starting). Now no remapping happens at all.

Have a great day!
