### ISSUE TITLE
How to use Kinto on FreeBSD?

### ISSUE THREAD

**Issue by probonopd** [rbreaves/kinto#365]
```
FreeBSD:/tmp/kinto% ./setup.py 
awk: can't open file /etc/os-release
 source line number 1
/bin/sh: ./system-config/dename.sh: not found

Kinto 1.2-4 build 98d5309
Type in Linux like it's a Mac.

Traceback (most recent call last):
  File "./setup.py", line 137, in <module>
    subprocess.check_call(shlex.split("./xkeysnail_service.sh"))
  File "/usr/local/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './xkeysnail_service.sh': './xkeysnail_service.sh'
```

**Comment by rbreaves** [comment]
Downloading your current release build right now, will setup a local dev VM to update Kinto for it.

**Comment by probonopd** [comment]
Thank you very much for looking into it. This is tremedous help.

**Comment by rbreaves** [comment]
So I have a new branch called hellosystem that updates are being pushed into. Just making notes atm of what needs to be done/differs.

This will be added soon as it takes care of some of the presetup stuff.
```
sudo pkg install python3
sudo python3 -m ensurepip
```

**Comment by rbreaves** [comment]
Some progress has been made but I will work on this a bit later. I think all of the presetup stuff has been taken care of but things relating to sudo.d and systemd will likely have to be updated so that Kinto can install without systemd.

**Comment by rbreaves** [comment]
I made a few additional quick changes and manually enabled the mac layout in kinto.py and then ran it via this command..

```
sudo xkeysnail ~/.config/kinto/kinto.py
```

And I have bad news, it appears like Kinto does not currently work under FreeBSD and I am not entirely sure why. I assume how it handles key input is just likely a bit different and that results in the applications not getting the remapped input. Oddly enough however, the terminal, qterminal and sublime_text are detected properly and the script is attempting to change the keymaps.. it just isn't sending the keymaps to /dev/uinput apparently otherwise the new keypresses would be going through and my actual ones would be suppressed. I guess x11 is not much different under FreeBSD vs Linux - but there is something different about key input.

So really.. unless I can find the fix for xkeysnail to operate as expected on FreeBSD it won't make much more sense to spend time on fixing up the installer. I will try and revisit this later - but the focus is now shifting towards understanding how key input happens under FreeBSD and whether or not xkeysnail can be updated to work on FreeBSD.

![image](https://user-images.githubusercontent.com/10969616/103469919-d27b5880-4d30-11eb-9932-ad82fb0313f7.png)

**Comment by rbreaves** [comment]
Posted an issue ticket with the folks at xkeysnail, no idea if they'll get back with me or not, but figure I am at a point with it where they might have better insights than me since I am not getting any obvious errors thrown at me to help me investigate.

https://github.com/mooz/xkeysnail/issues/117

**Comment by rbreaves** [comment]
I am wondering if this is related or not, seems to suggest the uinput (userspace input devices) were out of scope in adding evdev support natively to the freebsd kernel. It goes on to mention this input driver xf86-input-evdev, so perhaps xkeysnail support would need to come about by interacting it?

**Comment by probonopd** [comment]
Thank you very much for looking into this @rbreaves. Let's see what the xkeysnail people will say.

**Comment by louies0623** [comment]
@probonopd  This project has a new branch being maintained, and the author of this project has stopped maintaining it.
https://github.com/joshgoebel/keyszer
