### ISSUE TITLE
Exception on making Kinto tray enabled

### ISSUE THREAD

**Issue by bhedavivek** [rbreaves/kinto#383]
**Describe the bug**
Clicking on tray enabled raises an exception. This is happening because the `$HOME/.config/kinto/kintotray.py` is not executable when installed. chmodding `$HOME/.config/kinto/kintotray.py` fixes the issue.

Re-installing Kinto does not fix the issue. The file in question was updated in the recent future and my suspicion is that its permissions were updated as well.

**Distro:**
```
krypton@pop-os:~$ uname -a
Linux pop-os 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:51: DeprecationWarning: Gtk.Misc.set_alignment is deprecated                                                                         │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   label.set_alignment(1, 0)                                                                                                                                                       │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:107: DeprecationWarning: Vte.Terminal.spawn_sync is deprecated                                                                       │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   terminal.spawn_sync(                                                                                                                                                            │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:1070: DeprecationWarning: Vte.Terminal.feed_child_binary is deprecated                                                               │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   terminal.feed_child_binary(query)                                                                                                                                               │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:136: DeprecationWarning: Gtk.Widget.modify_bg is deprecated                                                                          │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   status_hbox.modify_bg(Gtk.StateFlags.NORMAL, Gdk.color_parse("#2d303b"))                                                                                                        │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:182: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   edititem_tweaks = Gtk.MenuItem("Tweaks")                                                                                                                                        │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:185: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   edititem_config = Gtk.MenuItem("Kinto Config (shortcuts)")                                                                                                                      │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:188: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   edititem_service = Gtk.MenuItem("Kinto Service")                                                                                                                                │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:191: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   edititem_shortcuts = Gtk.MenuItem("System Shortcuts")                                                                                                                           │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:194: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   edititem_language = Gtk.MenuItem("Change Language")                                                                                                                             │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:208: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   helpitem_support = Gtk.MenuItem("Support")                                                                                                                                      │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: /home/krypton/.config/kinto/gui/kinto-gui.py:212: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   helpitem_about = Gtk.MenuItem("About")                                                                                                                                          │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: Traceback (most recent call last):                                                                                                                                                │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   File "/home/krypton/.config/kinto/gui/kinto-gui.py", line 600, in checkTray                                                                                                     │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:     Popen([os.environ['HOME']+'/.config/kinto/kintotray.py'])                                                                                                                     │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__                                                                                                                  │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:     self._execute_child(args, executable, preexec_fn, close_fds,                                                                                                                  │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child                                                                                                           │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]:     raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                  │
│Jan 31 19:24:04 pop-os kinto.desktop[18914]: PermissionError: [Errno 13] Permission denied: '/home/krypton/.config/kinto/kintotray.py'                                                                                         │
│Jan 31 19:24:05 pop-os kinto.desktop[18975]: TERM environment variable not set.
```

**Comment by rbreaves** [comment]
Thank you for notifying, must have occurred when I re-organized the file/folder structure. I am surprised more haven't reported this issue. Will fix immediately.
