### ISSUE TITLE
[BUG] Lubuntu 20.04.2 (LXQt) not working (partial solution, see 1st post)

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#402]
Bare Metal install on Acer Aspire 5 Slim A515-43
Lubuntu 20.04.2 LTS
DE: LXQt

++++++++++++++++++++++

EDIT: Partial fix to at least get Kinto working on Lubuntu: 

`sudo apt install gir1.2-vte-2.91`

Before running Kinto setup, open the "Shortcut Keys" app and change the shortcut (line number changes, might be 32 or 33) for "Show/hide main menu" to something like Win+M (will show up as Meta+M). 

EDIT 2: To get Kinto mapping working in the default Lubuntu QTerminal app: 

Open `~/.config/kinto/kinto.py` and add `"qterminal"` to the end of the line near the top of the file that lists the `WM_CLASS` name of various terminal applications. Use the Kinto GUI to restart Kinto. 

++++++++++++++++++++++

I used `2>&1 | tee filename.txt` to make all these text files. Original formatting and colors seem to be retained if you just `cat` the text file from a terminal. 

Output from running `setup.py` (Kinto setup triggers many packages to be installed on a fresh Lubuntu install): 

[setup_output_lubuntu.txt](https://github.com/rbreaves/kinto/files/6007109/setup_output_lubuntu.txt)

=========

Output from trying to run `kinto-gui.py` manually: 

[kinto_gui_error.txt](https://github.com/rbreaves/kinto/files/6007111/kinto_gui_error.txt)

=========

Output from trying to run `kintotray.py` manually: 

[kintotray_error.txt](https://github.com/rbreaves/kinto/files/6007117/kintotray_error.txt)

=========

Xkeysnail status immediately after going through Kinto setup: 

[xkeysnail_status_after_install.txt](https://github.com/rbreaves/kinto/files/6007118/xkeysnail_status_after_install.txt)

=========

Xkeysnail status after manual "systemctl restart": 

[xkeysnail_status_after_systemctl_restart.txt](https://github.com/rbreaves/kinto/files/6007120/xkeysnail_status_after_systemctl_restart.txt)

=========

Process is running fine after manually starting or restarting. Alt+Tab task switching (window cycling) stops working when the service is running. Alt+T, Alt+Q, Alt+W, Alt+N and other shortcuts don't appear to do anything. The Lubuntu keyboard shortcut preferences dialog seems very rudimentary and contains no option resembling "Cycle windows" or "Switch applications" or "Task switcher" or anything else I can associate with the standard Alt+Tab (Cmd+Tab) function. 

If I can run any other commands or look at config files or something to provide more information, let me know. 

=========

Everything below is unrelated to Kinto: 

For future reference in case me or anyone else wants to ever run Lubuntu on this same hardware (Acer Aspire 5 Slim A515-43), I found a way to fix the stupidity of the default touchpad settings, which can't be fixed through the provided Lubuntu/LXQt touchpad settings GUI. I have set an exectuble shell script called `xinput.sh` to run at startup with this text inside: 

```
#!/bin/sh

xinput set-button-map 14 1 1 3 4 5 6 7
xinput set-prop "SYNA7DB5:01 06CB:CD41 Touchpad" "libinput Tapping Enabled" 1
```

The second line enables tap-to-click (why isn't this the default on every distro in 2021?) and the first line disables the middle mouse click on the touchpad, replacing it with the left mouse click. So the bottom edge of the touchpad is now Left-Left-Right, where the right-click is only activated if you press down on the far right corner of the touchpad. Replace the "1 1 3 4 5 6 7" with "1 1 1 4 5 6 7" if you want the touchpad click to only invoke a left-click. Use "1 2 3 4 5 6 7" to put it back to the unfortunate default of Left-Middle-Right. 

The reason this default setup is such a problem on this machine is that you can't reliably get a left-click unless you hit the very bottom-left corner of the touchpad, and you can't get a right-click unless you hit the bottom-right corner of the touchpad. Any other physical click on the touchpad yields a middle-click, if you are more than about 10% of the width of the touchpad away from the corner. Making everything worse, the touchpad is physically off-center to the left rather than centered under the space bar. So reaching the left-click corner with the right thumb as I am used to from almost two decades of using Mac trackpads is... very awkward. 

Hopefully this `xinput` trick will also make XFCE usable on this machine. 

To do something similar on a different machine you will need to modify the script with info from the output of `xinput` and then `xinput "DEVICENAME AND NUMBERS"` like this: 

```
$ xinput

⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ SYNA7DB5:01 06CB:CD41 Mouse               id=13   [slave  pointer  (2)]
⎜   ↳ SYNA7DB5:01 06CB:CD41 Touchpad            id=14   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Acer Wireless Radio Control               id=6    [slave  keyboard (3)]
    ↳ Power Button                              id=7    [slave  keyboard (3)]
    ↳ Video Bus                                 id=8    [slave  keyboard (3)]
    ↳ Video Bus                                 id=9    [slave  keyboard (3)]
    ↳ Power Button                              id=10   [slave  keyboard (3)]
    ↳ Sleep Button                              id=11   [slave  keyboard (3)]
    ↳ HD User Facing: HD User Facing            id=12   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=15   [slave  keyboard (3)]
    ↳ Acer WMI hotkeys                          id=16   [slave  keyboard (3)]

$ xinput "SYNA7DB5:01 06CB:CD41 Touchpad"

Device 'SYNA7DB5:01 06CB:CD41 Touchpad':
        Device Enabled (156):   1
        Coordinate Transformation Matrix (158): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        libinput Tapping Enabled (307): 1
        libinput Tapping Enabled Default (308): 0
        libinput Tapping Drag Enabled (309):    1                                                                                                                                            
        libinput Tapping Drag Enabled Default (310):    1                                                                                                                                    
        libinput Tapping Drag Lock Enabled (311):       0                                                                                                                                    
        libinput Tapping Drag Lock Enabled Default (312):       0                                                                                                                            
        libinput Tapping Button Mapping Enabled (313):  1, 0                                                                                                                                 
        libinput Tapping Button Mapping Default (314):  1, 0                                                                                                                                 
        libinput Natural Scrolling Enabled (291):       0                                                                                                                                    
        libinput Natural Scrolling Enabled Default (292):       0                                                                                                                            
        libinput Disable While Typing Enabled (315):    1                                                                                                                                    
        libinput Disable While Typing Enabled Default (316):    1                                                                                                                            
        libinput Scroll Methods Available (293):        1, 1, 0                                                                                                                              
        libinput Scroll Method Enabled (294):   1, 0, 0                                                                                                                                      
        libinput Scroll Method Enabled Default (295):   1, 0, 0                                                                                                                              
        libinput Click Methods Available (317): 1, 1                                                                                                                                         
        libinput Click Method Enabled (318):    1, 0                                                                                                                                         
        libinput Click Method Enabled Default (319):    1, 0                                                                                                                                 
        libinput Middle Emulation Enabled (320):        0                                                                                                                                    
        libinput Middle Emulation Enabled Default (321):        0                                                                                                                            
        libinput Accel Speed (298):     0.000000                                                                                                                                             
        libinput Accel Speed Default (299):     0.000000                                                                                                                                     
        libinput Left Handed Enabled (303):     0                                                                                                                                            
        libinput Left Handed Enabled Default (304):     0
        libinput Send Events Modes Available (276):     1, 1
        libinput Send Events Mode Enabled (277):        0, 0
        libinput Send Events Mode Enabled Default (278):        0, 0
        Device Node (279):      "/dev/input/event11"
        Device Product ID (280):        1739, 52545
        libinput Drag Lock Buttons (305):       <no items>
        libinput Horizontal Scroll Enabled (306):       1
```

So the "14" from the shell script is from where it says `id=14` next to the name of the touchpad hardware device.

**Comment by RedBearAK** [comment]
For easier searchability: 

The `kintotray` error: 

```
Traceback (most recent call last):
  File "/home/kris/.config/kinto/kintotray.py", line 6, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

The `kinto-gui` error: 

```
Traceback (most recent call last):
  File "/home/kris/.config/kinto/gui/kinto-gui.py", line 5, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
```

**Comment by rbreaves** [comment]
Just skimming atm but " Namespace Vte not available" is an old one referenced in #302

Installing this would fix it or the equivalent for any package manager. Would fix the main gui app, perhaps not the system tray or other errors though.
```
sudo apt install vte-2.91
```

**Comment by rbreaves** [comment]
I believe some DE's use AppIndicator3 and some don't but that would certainly be a requirement for the system tray. It simply won't be available for all DE's that don't support it though. I have no plans to write it in anything else since it has decent coverage and the only other DE I would even consider writing another system tray app for in the future would be KDE due to its user base. It took me a good bit of time to write the one that I did write lol.

**Comment by RedBearAK** [comment]
No package "vte" on Lubuntu. Here's the output from `apt search vte`: 

```
Sorting... Done
Full Text Search... Done
antimicro/focal 2.23-2build1 amd64
  GUI for mapping keyboard keys and mouse controls to a gamepad

cyrus-clients/focal 3.0.13-5 amd64
  Cyrus mail system - test clients

evtest/focal 1:1.34-1 amd64
  utility to monitor Linux input device events

fonts-firacode/focal,focal 2+dfsg1-1 all
  Monospaced font with programming ligatures

gir1.2-vte-2.91/focal-updates 0.60.3-0ubuntu1~20.04 amd64
  GObject introspection data for the VTE library

joystick/focal 1:1.7.0-1 amd64
  set of testing and calibration tools for joysticks

libevt-utils/focal 20181227-1.1 amd64
  Windows Event Log (EVT) format access library -- Utilities

libghc-gi-vte-dev/focal 2.91.19-1build1 amd64
  VTE bindings

libghc-gi-vte-doc/focal,focal 2.91.19-1build1 all
  VTE bindings; documentation

libghc-gi-vte-prof/focal 2.91.19-1build1 amd64
  VTE bindings; profiling libraries

librust-vte-dev/focal 0.3.3-1 amd64
  Parser for implementing terminal emulators - Rust source code

libtsm-dev/focal 3-1build1 amd64
  Terminal-emulator State Machine - development

libtsm3/focal 3-1build1 amd64
  Terminal-emulator State Machine - runtime

libumockdev-dev/focal-updates 0.14.1-1ubuntu0.1 amd64
  development files and documentation for libumockdev

libumockdev0/focal-updates 0.14.1-1ubuntu0.1 amd64
  hardware mocking testbed for bug reports and regression tests

libvte-2.91-0/focal-updates 0.60.3-0ubuntu1~20.04 amd64
  Terminal emulator widget for GTK+ 3.0 - runtime files

libvte-2.91-common/focal-updates 0.60.3-0ubuntu1~20.04 amd64
  Terminal emulator widget for GTK+ 3.0 - common files

libvte-2.91-dev/focal-updates 0.60.3-0ubuntu1~20.04 amd64
  Terminal emulator widget for GTK+ 3.0 - development files

libvte-2.91-doc/focal-updates,focal-updates 0.60.3-0ubuntu1~20.04 all
  Terminal emulator widget for GTK+ 3.0 - documentation

libvte-common/focal,focal 1:0.28.2-6build1 all
  Terminal emulator widget for GTK+ 2.x - common files

libvte-dev/focal 1:0.28.2-6build1 amd64
  Terminal emulator widget for GTK+ 2.0 - development files

libvte9/focal 1:0.28.2-6build1 amd64
  Terminal emulator widget for GTK+ 2.0 - runtime files

libvted-3-0/focal 3.9.0-3build2 amd64
  Terminal emulator widget for GTK+ - D bindings

libvted-3-dev/focal 3.9.0-3build2 amd64
  Terminal emulator widget for GTK+ - development files for D

libvterm-bin/focal 0.1.2-2 amd64
  abstract terminal library (utility programs)

libvterm-dev/focal 0.1.2-2 amd64
  abstract terminal library (development files)

libvterm0/focal 0.1.2-2 amd64
  abstract terminal library

lilyterm/focal 0.9.9.4+git20150208.f600c0-5 amd64
  Light and eazy-to-use terminal emulator for X

lxterminal/focal 0.3.2-1 amd64
  LXDE terminal emulator

openvswitch-vtep/focal-updates,focal-security 2.13.1-0ubuntu0.20.04.4 amd64
  Open vSwitch VTEP utilities

ovn-controller-vtep/focal-updates 20.03.1-0ubuntu1.2 amd64
  OVN vtep controller

pangoterm/focal 0~bzr613-1 amd64
  GTK/Pango-based terminal

sakura/focal 3.7.0-1 amd64
  simple but powerful libvte-based terminal emulator

termit/focal 3.1-1 amd64
  Simple terminal emulator based on vte library, embedded lua

texlive-publishers/focal,focal 2019.202000218-1 all
  TeX Live: Publisher styles, theses, etc.

texlive-science/focal,focal 2019.202000218-1 all
  TeX Live: Mathematics, natural sciences, computer science packages

vim-syntax-gtk/focal,focal 20110314-1 all
  Syntax files to highlight GTK+ keywords in vim

virgl-server/focal 0.8.2-1ubuntu1 amd64
  virtual GPU for KVM virtualization - vtest server used

```

Best guess at the moment: The `gir1.2-vte-2.91` package?

**Comment by RedBearAK** [comment]
Going ahead with this to see what happens: 

```
kris@Aspire5-Lubuntu:~/Downloads/kinto$ sudo apt install gir1.2-vte-2.91
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libvte-2.91-0 libvte-2.91-common
The following NEW packages will be installed:
  gir1.2-vte-2.91 libvte-2.91-0 libvte-2.91-common
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 212 kB of archives.
After this operation, 756 kB of additional disk space will be used.
Do you want to continue? [Y/n]    
```

**Comment by RedBearAK** [comment]
Kinto GUI has successfully popped up, leaving all this in the terminal window (probably the same stuff I posted before): 

```
/home/kris/.config/kinto/gui/kinto-gui.py:51: DeprecationWarning: Gtk.Misc.set_alignment is deprecated
  label.set_alignment(1, 0)
keyboard is not set
(1200, 720)
(1200, 720)

(kinto-gui.py:10457): Gtk-WARNING **: 18:23:02.810: Attempting to add a widget with type GtkBox to a container of type GtkWindow, but the widget is already inside a container of type GtkOverlay, please remove the widget from its existing container first.
/home/kris/.config/kinto/gui/kinto-gui.py:1113: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  previous = Gtk.Button("Uninstall")
/home/kris/.config/kinto/gui/kinto-gui.py:1115: DeprecationWarning: Gtk.Widget.set_margin_right is deprecated
  previous.set_margin_right(206)
/home/kris/.config/kinto/gui/kinto-gui.py:1118: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  onward = Gtk.Button("Continue")
/home/kris/.config/kinto/gui/kinto-gui.py:1132: DeprecationWarning: Gtk.Widget.set_margin_left is deprecated
  self.grid.set_margin_left(157)
/home/kris/.config/kinto/gui/kinto-gui.py:1172: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  previous = Gtk.Button("")
/home/kris/.config/kinto/gui/kinto-gui.py:1245: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  previous = Gtk.Button("")
/home/kris/.config/kinto/gui/kinto-gui.py:1329: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  previous = Gtk.Button("")
/home/kris/.config/kinto/gui/kinto-gui.py:1390: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  previous = Gtk.Button("       ")
/home/kris/.config/kinto/gui/kinto-gui.py:107: DeprecationWarning: Vte.Terminal.spawn_sync is deprecated
  terminal.spawn_sync(
/home/kris/.config/kinto/gui/kinto-gui.py:1070: DeprecationWarning: Vte.Terminal.feed_child_binary is deprecated
  terminal.feed_child_binary(query)
60
/home/kris/.config/kinto/gui/kinto-gui.py:136: DeprecationWarning: Gtk.Widget.modify_bg is deprecated
  status_hbox.modify_bg(Gtk.StateFlags.NORMAL, Gdk.color_parse("#2d303b"))
/home/kris/.config/kinto/gui/kinto-gui.py:182: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  edititem_tweaks = Gtk.MenuItem("Tweaks")
/home/kris/.config/kinto/gui/kinto-gui.py:185: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  edititem_config = Gtk.MenuItem("Kinto Config (shortcuts)")
/home/kris/.config/kinto/gui/kinto-gui.py:188: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  edititem_service = Gtk.MenuItem("Kinto Service")
/home/kris/.config/kinto/gui/kinto-gui.py:191: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  edititem_shortcuts = Gtk.MenuItem("System Shortcuts")
/home/kris/.config/kinto/gui/kinto-gui.py:194: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  edititem_language = Gtk.MenuItem("Change Language")
/home/kris/.config/kinto/gui/kinto-gui.py:208: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  helpitem_support = Gtk.MenuItem("Support")
/home/kris/.config/kinto/gui/kinto-gui.py:212: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  helpitem_about = Gtk.MenuItem("About")

```

Setup GUI does not want to capture the Win key (it's being used to activate the Lubuntu/LXQt main menu), so can't continue at the moment. Will try to bypass by changing the shortcut for the menu. 

Changed to physical Win+M which is shown as Meta+M. Kinto service status is showing `failed` at the moment. So should be the original key mapping. 

Got through the installer now and the final terminal/GUI window showed up. Showing Kinto as "active" in green. 

Hey... hey, hey, HEY! Guess what? It works. 

Alt+Tab
Alt+N
Alt+T
Alt+W
Alt+Q
Alt+X/C/V

... Alt+H not so much. So same problem as Cinnamon, and I can't find any shortcut listed for anything like "minimize window", so no idea why it would be blocked in this DE. 

But mostly working. 

This is the entirety of the Shortcut Keys app list of shortcuts. It's pretty odd. 

![Lubuntu-LXQt_shortcut_keys1](https://user-images.githubusercontent.com/64876997/108454291-933d9400-7218-11eb-8c5c-8f0440305e2e.jpg)

![Lubuntu-LXQt_shortcut_keys2](https://user-images.githubusercontent.com/64876997/108454299-96388480-7218-11eb-986f-9201a018d3ad.jpg)

**Comment by RedBearAK** [comment]
So were all three of these packages necessary, or just the main `libvte` package? 

`libvte-2.91-0`
`libvte-2.91-common`
`gir1.2-vte-2.91`

**Comment by RedBearAK** [comment]
Looks like the main package to tell people to install is the `gir1.2-vte-2.91` package. The Kinto GUI won't work with only the `libvte` packages installed. 

I uninstalled Kinto and purged all the packages and only installed `libvte-2.91-0`, which brought along `libvte-2.91-common`. But the GUI would not run until I reinstalled `gir1.1-vte-2.91`. 

Looks like the mapping is not working right in the default terminal, which is QTerminal 0.14.1 on Lubuntu. It's the only terminal installed by default. Let me know if there is a way to help troubleshoot that.

**Comment by RedBearAK** [comment]
Updated the initial post with the partial fix identified above. 

So the fix that would let this issue be closed is: 

If DE is LXQt: 
Install `gir1.2-vte2.91`
Maybe throw a warning that the tray indicator won't work. 

That's it. 

![Lubuntu_neofetch](https://user-images.githubusercontent.com/64876997/108457370-01855500-721f-11eb-8291-c215d965bb95.jpg)

**Comment by rbreaves** [comment]
Running or installing xprop can help you identify the proper terminal name.

```
xprop -spy
```

It’s pretty trivial then to add the wm_class name to ~/.config/kinto/kinto.py.

There’s an array called terminals, just add it to the list. Linux terminals pretty well all follow the same shortcuts thankfully.

**Comment by RedBearAK** [comment]
@rbreaves 

So, that was a bit confusing. But it looks like wm_class is "qterminal". Should have said, "Run `xprop -spy | grep -i wm_class` and then click on the titlebar of the terminal window."

```
WM_CLASS(STRING) = "qterminal", "qterminal"
```

I added it to `kinto.py` at the end of the string of terminals. Restarted Kinto with the GUI. It appears to work. 

Going to add it to the default `kinto.py` for the next release?

**Comment by RedBearAK** [comment]
Added a couple of lines in PR #429 (Fix for Ubuntu) to install gir1.2-vte-2.91 package on Lubuntu so that setup can complete and show the GUI. Tested to work on a clean boot of Lubuntu live environment. The only way to tell it's Lubuntu is referencing DESKTOP_SESSION or XDG_CURRENT_DESKTOP. 

I have to look at setting up a Y/N prompt for the user to verify that they have reassigned the shortcut for the main menu from "Super_L", so that they can actually get through the installer. Or a new prompt screen in the GUI app if Lubuntu is detected.

**Comment by RedBearAK** [comment]
Resolved.
