### ISSUE TITLE
Cannot install on Arch Linux-KDE

### ISSUE THREAD

**Issue by Frityet** [rbreaves/kinto#636]
**Describe the bug**
When attempting to install the program on Arch Linux, running KDE plasma v5.24, X11 the install completes but the GUI never shows, and when trying to manually launch the GUI, i get this error
```yaml
Traceback (most recent call last):
  File "/home/frityet/.config/kinto/gui/kinto-gui.py", line 7, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
```

I have checked and confirmed that `Vte` is installed (`pip install Vte`),  all of the rest of the dependencies are also installed.

**Expected behavior**
The Kinto.sh GUI to show up and identify my keyboard.

**Install Type:** Bare Metal
**Distro:** Arch Linux
```c
❯ uname -ar
Linux FritPC 5.16.10-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 16 Feb 2022 19:35:21 +0000 x86_64 GNU/Linux
```
**DE:** KDE
**Branch:** master,
**Commit:** latest

Logs and status if relevant
```sh
# xkeysnail
sudo systemctl status xkeysnail
sudo journalctl --unit=xkeysnail.service -b
```
```yaml
❯ sudo systemctl status xkeysnail
● xkeysnail.service - xkeysnail
     Loaded: loaded (/usr/lib/systemd/system/xkeysnail.service; disabled; vendor preset: disabled)
     Active: active (running) since Sat 2022-03-12 19:57:18 PST; 2min 22s ago
   Main PID: 23288 (sudo)
      Tasks: 2 (limit: 38444)
     Memory: 18.5M
        CPU: 1.037s
     CGroup: /system.slice/xkeysnail.service
             ├─23288 /usr/bin/sudo /bin/bash -c "/usr/bin/xhost +SI:localuser:root && /home/frityet/.config/kinto/killdups.sh && /usr/bin/xk>
             └─23290 /usr/bin/python /usr/bin/xkeysnail --quiet --watch /home/frityet/.config/kinto/kinto.py

Mar 12 19:57:18 FritPC systemd[1]: Started xkeysnail.
Mar 12 19:57:18 FritPC sudo[23288]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/frityet/.>
Mar 12 19:57:18 FritPC sudo[23288]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Mar 12 19:57:18 FritPC sudo[23291]: localuser:root being added to access control list

#

❯ sudo journalctl --unit=xkeysnail.service -b
Mar 12 19:53:16 FritPC systemd[1]: Started xkeysnail.
Mar 12 19:53:16 FritPC sudo[22198]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/frityet/.>
Mar 12 19:53:16 FritPC sudo[22198]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Mar 12 19:53:16 FritPC sudo[22201]: localuser:root being added to access control list
Mar 12 19:56:41 FritPC systemd[1]: Stopping xkeysnail...
Mar 12 19:56:41 FritPC sudo[23046]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/sudo pkill -f bin/xkeysnail && exit 0
Mar 12 19:56:41 FritPC sudo[23046]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Mar 12 19:56:41 FritPC sudo[23048]:     root : PWD=/ ; USER=root ; COMMAND=/usr/sbin/pkill -f bin/xkeysnail
Mar 12 19:56:41 FritPC sudo[23048]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Mar 12 19:56:41 FritPC sudo[23048]: pam_unix(sudo:session): session closed for user root
Mar 12 19:56:41 FritPC sudo[23046]: pam_unix(sudo:session): session closed for user root
Mar 12 19:56:41 FritPC systemd[1]: xkeysnail.service: Control process exited, code=killed, status=15/TERM
Mar 12 19:56:41 FritPC sudo[22198]: pam_unix(sudo:session): session closed for user root
Mar 12 19:56:41 FritPC systemd[1]: xkeysnail.service: Failed with result 'signal'.
Mar 12 19:56:41 FritPC systemd[1]: Stopped xkeysnail.
Mar 12 19:56:41 FritPC systemd[1]: xkeysnail.service: Consumed 2.042s CPU time.
Mar 12 19:57:18 FritPC systemd[1]: Started xkeysnail.
Mar 12 19:57:18 FritPC sudo[23288]:     root : PWD=/ ; USER=root ; COMMAND=/bin/bash -c /usr/bin/xhost +SI:localuser:root && /home/frityet/.>
Mar 12 19:57:18 FritPC sudo[23288]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Mar 12 19:57:18 FritPC sudo[23291]: localuser:root being added to access control list

```

**Comment by Frityet** [comment]
These errors also appear when the installation occurs

```yaml
ln: failed to create symbolic link '/etc/systemd/system/graphical.target.wants/xkeysnail.service': No such file or directory
Failed to create soft symlink for graphical target...
Removed /etc/systemd/system/xkeysnail.service.
Adding xhost fix...
```

**Comment by Frityet** [comment]
Fixed by reinstalling Arch

**Comment by rbreaves** [comment]
Ouch.. hate to hear you had to reinstall it.. One possible scenario is you had 2 version of python installed. Specifying its entire path to one or the other might have resolved it without a full reinstall.
