### ISSUE TITLE
Not working on Parrot Linux: GLib error

### ISSUE THREAD

**Issue by Danrancan** [rbreaves/kinto#843]
**Describe the bug**
After running the setup.py script in the latest version of Parrot OS I get:

```
If the setup wizard fails to appear then please run this command.
~/.config/kinto/gui/kinto-gui.py
```
The wizard fails to open at all so I run ~/.config/kinto/gui/kinto-gui.py
and get the following:

Traceback (most recent call last):
  File "/home/rockstar/.config/kinto/gui/kinto-gui.py", line 1478, in <module>
    win = MyWindow()
          ^^^^^^^^^^
  File "/home/rockstar/.config/kinto/gui/kinto-gui.py", line 101, in __init__
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(path, width, height, preserve_aspect_ratio)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/rockstar/.config/kinto/kinto-color.svg” (3)
`
Application not working on macbook 11,3 running Parrot OS. How can I fix this?

**Comment by RedBearAK** [comment]
@Danrancan 

Try reading through this:

https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/159
