### ISSUE TITLE
kinto-gui.py fails on Vte dependency 

### ISSUE THREAD

**Issue by eljfe** [rbreaves/kinto#865]
**Describe the bug**

```bash
$ ./kinto-gui.py 
Traceback (most recent call last):
  File "/home/bossy/.config/kinto/gui/./kinto-gui.py", line 7, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
```

**Expected behavior**

`kinto-gui.py` runs.  Supporting packages are installable.

I followed the youtube video. Then tried the python script per the instructions, but possible I missed a step.

**Install Type:** Bare Metal
**Distro:** Debian 12 Bworm
**DE:** XFCE
**Branch:** master
**Commit:** 4a3bfe7

Logs and status if relevant
```
# xkeysnail

sudo systemctl status xkeysnail :
xkeysnail.service - xkeysnail
     Loaded: loaded (/lib/systemd/system/xkeysnail.service; disabled; >
     Active: inactive (dead)

sudo journalctl --unit=xkeysnail.service -b
-- No entries --

# xkb
systemctl --user status keyswap
Unit keyswap.service could not be found.

journalctl --user-unit=keyswap.service -b
Unit keyswap.service could not be found.
```

**Screenshots**

**Additional context**

graphical kinto.sh dies silently.

`Vte` is not part of the apt repository, and of course pip no longer does system wide installs.  Kind of stuck here.

**Comment by chrisbc8000** [comment]
install gir1.2-vte-2.91

this works for me, install is successful,
