### ISSUE TITLE
Cannot install - setup wizard fails to appear.  Can't run kinto-gui.py.  

### ISSUE THREAD

**Issue by senesi1** [rbreaves/kinto#888]
**Describe the bug**
Attempted install.  Received terminal output 'Kinto install is complete.'  

**Expected behavior**
setup wizard should have appeared.  When I tried to run kinto/gui/kinto-gui.py, I got...

**python3 kinto/gui/kinto-gui.py 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Traceback (most recent call last):
  File "/home/la-jsenesi/.config/kinto/gui/kinto-gui.py", line 25, in <module>
    class MyWindow(Gtk.Window):
  File "/home/la-jsenesi/.config/kinto/gui/kinto-gui.py", line 36, in MyWindow
    setupwin = Gtk.Window()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
Exception ignored in atexit callback: <function kill_child at 0x74e639b51090>
Traceback (most recent call last):
  File "/home/la-jsenesi/.config/kinto/gui/kinto-gui.py", line 17, in kill_child
    if child_pid is None:
NameError: name 'child_pid' is not defined**

**Install Type:** Bare Metal or VM
**Distro:** Name + Version
**DE:** Gnome, XFCE, KDE
**Branch:** master, dev
**Commit:** git rev-parse --short HEAD

Logs and status if relevant
```
# xkeysnail
sudo systemctl status xkeysnail
sudo journalctl --unit=xkeysnail.service -b

# xkb
systemctl --user status keyswap
journalctl --user-unit=keyswap.service -b
```

**Screenshots**

**Additional context**

**Comment by RedBearAK** [comment]
@senesi1 

>  Authorization required, but no authorization protocol specified

It's always good to note which Linux distro you're using when you run into problems like this. Sometimes it's relevant. I believe the last time I ran into an error like that it was on openSUSE Tumbleweed. I never discovered the root cause of the error. There aren't many useful references to it online. 

Unless I am misremembering, the following command might help overcome the error, if you run this command before trying to run the Kinto GUI app command: 

```
xhost +local:
```

If that works, it may also allow the `xkeysnail` service (the actual keymapper) to start up successfully when you finish the install. In which case you can edit the `xkeysnail.service` unit file and add that command into the existing command string. 

Remember that you have to stop the service and issue `sudo systemctl daemon-reload` in order to get `systemd` to recognize that the service unit file has changed, before restarting the service. 

If you still can't get Kinto working after trying this, there is an alternative to Kinto called Toshy, which I created using Kinto's keymapper config file. It's pinned in my GitHub. You'll have to stop the Kinto service and disable its auto-start feature (or uninstall Kinto) in order to try Toshy, or they will conflict over needing to grab the `uinput` device. If you leave Kinto installed you can always return to trying Kinto by stopping Toshy's services and disabling it from auto-starting.

**Comment by senesi1** [comment]
@RedBearAK  
xhost +local:
That worked immediately.  I have Kinto running now.  Thanks so much for your prompt feedback and help.

**Comment by RedBearAK** [comment]
@senesi1 

Fabulous. Keep Toshy in mind if you have need of a Wayland session at some point. Kinto is still X11-only, and implementing Wayland support has been quite complicated.
